// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT65A253ftpwcK5Eag9g_2-UigjAURrF8',
    appId: '1:664966752885:web:9808c3e761ea508105e63c',
    messagingSenderId: '664966752885',
    projectId: 'docread-86b08',
    authDomain: 'docread-86b08.firebaseapp.com',
    storageBucket: 'docread-86b08.appspot.com',
    measurementId: 'G-ZVFQD5852M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm1ZSLsStU38WlJ8i_flNB83ltgirPeYM',
    appId: '1:664966752885:android:70f1ab9c18c1a03905e63c',
    messagingSenderId: '664966752885',
    projectId: 'docread-86b08',
    storageBucket: 'docread-86b08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT-ZIaiktV7Fd_Xl0b7qZVzSX3U6uek1k',
    appId: '1:664966752885:ios:3523a3990432308505e63c',
    messagingSenderId: '664966752885',
    projectId: 'docread-86b08',
    storageBucket: 'docread-86b08.appspot.com',
    iosClientId: '664966752885-hrf6pi8bseiru6urijcok2gs36s2v81u.apps.googleusercontent.com',
    iosBundleId: 'com.example.dmi2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT-ZIaiktV7Fd_Xl0b7qZVzSX3U6uek1k',
    appId: '1:664966752885:ios:d3c501beecf2e59605e63c',
    messagingSenderId: '664966752885',
    projectId: 'docread-86b08',
    storageBucket: 'docread-86b08.appspot.com',
    iosClientId: '664966752885-55uae6a9lvpnubmb3k1nlmu9dt253s74.apps.googleusercontent.com',
    iosBundleId: 'com.example.dmi2.RunnerTests',
  );
}
